<?php

/**
 * @file
 * Disable failed login errors on on the user login form.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function disable_login_errors_form_user_login_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'disable_login_errors_validate';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function disable_login_errors_form_user_login_block_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'disable_login_errors_validate';
}

/**
 * Implements hook_validate().
 *
 * Clears the message queue of errors after core login validation.
 */
function disable_login_errors_validate($form, &$form_state) {
  // Removes "Sorry, unrecognized username.", "Sorry, incorrect password."
  // and "The username $name has not been activated or is blocked.",
  // and any other login errors because they might be helpful to an attacker.
  $error_messages = backdrop_get_messages('error', TRUE);

  if (!empty($error_messages)) {
    // Resets the form error status so no form fields are highlighted in red.
    $form_state['rebuild'] = TRUE;
    form_clear_error();
  }
}
